# Site settings
title: DogOnt
email: dario.bonino@gmail.com
description: The DogOnt ontology documentation web site
url: http://iot-ontologies.github.io/dogont
baseurl: http://iot-ontologies.github.io/dogont
permalink: /:categories/:year/:title.html

markdown: redcarpet
redcarpet:
  extensions: ["hard_wrap", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "superscript"]
highlighter: pygments


