# Site settings
title: DogOnt
email: dario.bonino@gmail.com
description: The DogOnt ontology documentation web site
url: http://iot-ontologies.github.io/dogont
baseurl: /dogont
permalink: /:categories/:year/:title.html

highlighter: pygments


